pm uninstall -k --user 0 com.samsung.sree
pm uninstall -k --user 0 com.samsung.sree.countdown
pm uninstall -k --user 0 com.samsung.sree.classic
pm uninstall -k --user 0 com.samsung.sree.spin
pm uninstall -k --user 0 com.samsung.sree.digital
pm uninstall -k --user 0 com.microsoft.office.outlook
pm uninstall -k --user 0 com.google.android.apps.messaging
pm uninstall -k --user 0 com.samsung.android.bixby.agent
pm uninstall -k --user 0 com.samsung.android.bixby.wakeup