adb shell pm uninstall -k --user 0 com.samsung.sree
adb shell pm uninstall -k --user 0 com.samsung.sree.countdown
adb shell pm uninstall -k --user 0 com.samsung.sree.classic
adb shell pm uninstall -k --user 0 com.samsung.sree.spin
adb shell pm uninstall -k --user 0 com.samsung.sree.digital
adb shell pm uninstall -k --user 0 com.microsoft.office.outlook
adb shell pm uninstall -k --user 0 com.google.android.apps.messaging
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.agent
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.wakeup